### ISSUE TITLE
Rating system not working properly.

### ISSUE THREAD

**Issue by punit1108** [codearora/Book-Application#1]
<img width="475" alt="Screenshot 2024-06-02 at 12 35 59 PM" src="https://github.com/codearora/Book-Application/assets/7887355/e36d5081-4378-46cd-ac70-17bbfb943422">

As seen above, i am able to add whatever value of rating i like. Also i dont see the average rating of the book.

**Comment by codearora** [comment]
Hi Punit,

I have fixed below issues:
1) Rating is limited from 1 to 5.
2) Average rating of the book is shown above.
Please let me know about any further issues.

Thanks
Jai Arora

**Comment by codearora** [comment]
Since these 2 issues are fixed hence closing this.
